<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>FileRenamer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType Condition="'$(WindowsPackageType)' == ''">None</WindowsPackageType>
    <SelfContained>false</SelfContained>
    <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>
    <AppxManifest>Package.appxmanifest</AppxManifest>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
    <PackageReference Include="PDFtoImage" Version="4.1.1" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**" />
    <Content Include="tessdata\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

</Project>
